### ISSUE TITLE
fastplotlib stuff for release

### ISSUE THREAD

**Issue by kushalkolar** [flatironinstitute/ccn-software-fens-2024#19]
for the final build we should change things so:

- [ ] use `fastplotlib` from release, it auto gets the right `pygfx` and `wgpu` versions
- [ ] keep `simplejpeg` and `glfw`
- [ ] should we add `av` , `imageio` uses it for opening video files, if @clewis7 is showing imagewidget or other demos by opening small video files? https://pypi.org/project/av/

**Comment by clewis7** [comment]
I don't have any `ImageWidget` examples

**Comment by billbrod** [comment]
I believe I've made these changes in `main` now, can you confirm that it looks good to you?

**Comment by clewis7** [comment]
LGTM
